const RegistrationActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const AuthActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const DoctorSpecialtyActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const DoctorShowActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const DoctorAppointmentActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const NurseSpecialtyActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const NurseShowActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const NurseAppointmentActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const PharmaciesShowtActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const PharmacyOrderstActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

export {
  RegistrationActionTypes,
  AuthActionTypes,
  DoctorSpecialtyActionTypes,
  DoctorShowActionTypes,
  DoctorAppointmentActionTypes,
  NurseSpecialtyActionTypes,
  NurseShowActionTypes,
  NurseAppointmentActionTypes,
  PharmaciesShowtActionTypes,
  PharmacyOrderstActionTypes,
};
