const RegistrationActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const AuthActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const DoctorSpecialtyActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

const DoctorShowActionTypes = {
  FITCH_DATA_START: 'FETCH_DATA_START',
  FITCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

export {
  RegistrationActionTypes,
  AuthActionTypes,
  DoctorSpecialtyActionTypes,
  DoctorShowActionTypes,
};
